travis:
  secure:
    BINSTAR_TOKEN: Ip58hm73+hln0yvAiVfV3qe0YofonjxB0f6K86SUVi2gwt3+P9zSVroJPOPDeI/RvK/qS8ISdAaSujqb4eyURhPKQiHiBLjbBF/28IYHV1uT5t+VURCMo/WWs5zneyQwYx3P3T9O2r8yoprVNfS9xS6XY+p3ekrbWBIHIKLk1Ym14KSBAHkA4FR64AfCArX/TsEET1IBTFx1zkd+29QCAgBXcvhLAQ5nNj7gb1/+RQeP+wYfbgzJ/TitwoZcMVTP/fohmaklfvvpXvWYx6Q10PUC+/8BucmAxsGVvo1eNlwSLx9lUHkF0F4fMErStU/jlO8n752iqtwaMH1Z3b7s6Q+2pcAfoJsDXZyiiaLjxdoJHJrsTu+SHluxvh8F3dw+FFowVXMda9Y3NtjFjX1qVgzltjXScM6cDTDqnzFY1D9ZmSdwMtJ8xwMQzlCyhu3gyzrQeGsQC1LxrBuuN9JRy1QFOZ7AZpLTIeZGF9KwpyZaAQnVBAWO+lieGfrQ4/lDQycCpDu/qU0XrnWj1aA9gw8WQAHUUl612nB34Ag6Ro/GOm2C8xV6/22j3gCDH/oX8gf4bYaYHF9IYbEwxNnWcOBVfipD5Ik34kwnuWgW3wV5JVGE0cZTkjPD4al00e8h6GpOdrgUaazknwVAulW6I1+pbnsush51toXsDar5qhA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
